### ISSUE TITLE
Combine in to one shortcode?

### ISSUE THREAD

**Issue by mcangeli** [alexjustesen/custom-untappd-feeds#6]
Is it possible to list the profile info, the badges and checkins in one short code or is that a feature request?

**Comment by alexjustesen** [comment]
Going to begin working on this feature this week. Will build the first code push showing the profile info first, badges second then the activity feed.

**Comment by mcangeli** [comment]
Nice!

**Comment by alexjustesen** [comment]
Just published 2018.12-beta with a combined shortcode and a bunch of other changes. Let me know your thoughts.

**Comment by mcangeli** [comment]
There's something in the new code that breaks everything else. (I think there's something that isn't closed?)

**Comment by alexjustesen** [comment]
Interesting, I'll take a look and get back to you.

**Comment by alexjustesen** [comment]
Can you go into the plugin settings in the WP dashboard and make sure your api keys and timeout are set by saving the values?

**Comment by mcangeli** [comment]
Done. And the same:

> [Fri Nov 30 17:10:35.065726 2018] [:error] [pid 3282] [client 50.233.145.102:60056] PHP Fatal error:  Cannot access empty property in /var/www/gabeerguide/wp-content/plugins/custom-untappd-feeds-master/includes/class-custom-untappd-feeds-api.php on line 47, referer: https://gabeerguide.com/
>[Fri Nov 30 17:10:40.831044 2018] [:error] [pid 3709] [client 66.249.92.202:50195] PHP Fatal error:  Cannot access empty property in /var/www/gabeerguide/wp-content/plugins/custom-untappd-feeds-master/includes/class-custom-untappd-feeds-api.php on line 47

**Comment by alexjustesen** [comment]
Found the issue and released 2018.12-beta2 with the bug fix.

**Comment by mcangeli** [comment]
Works!

Thanks!

**Comment by alexjustesen** [comment]
Closing this request, if you find anything else or have another request feel free to open an issue.
